// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier.js";
import type { Node } from "./Node.js";
import type { ObjectProperty } from "./ObjectProperty.js";

export type Annotation = { "type": "Annotation", name: Node<Identifier> | null, properties: Array<Node<ObjectProperty>> | null, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
