// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expr } from "./Expr.js";
import type { NonCodeMeta } from "./NonCodeMeta.js";

export type ArrayExpression = { "type": "ArrayExpression", elements: Array<Expr>, nonCodeMeta?: NonCodeMeta, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
