// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId.js";
import type { ApiObjectId } from "./FrontendApi.js";
import type { ExtrudeMethod, ModelingCmd } from "./ModelingCmd.js";
import type { NodePath } from "./NodePath.js";
import type { PlaneName } from "./PlaneName.js";
import type { SourceRange } from "./SourceRange.js";

export type Artifact = { "type": "compositeSolid" } & CompositeSolid | { "type": "plane" } & Plane | { "type": "path" } & Path | { "type": "segment" } & Segment | { "type": "solid2d" } & Solid2d | { "type": "primitiveFace" } & PrimitiveFace | { "type": "primitiveEdge" } & PrimitiveEdge | { "type": "planeOfFace" } & PlaneOfFace | { "type": "startSketchOnFace" } & StartSketchOnFace | { "type": "startSketchOnPlane" } & StartSketchOnPlane | { "type": "sketchBlock" } & SketchBlock | { "type": "sketchBlockConstraint" } & SketchBlockConstraint | { "type": "sweep" } & Sweep | { "type": "wall" } & Wall | { "type": "cap" } & Cap | { "type": "sweepEdge" } & SweepEdge | { "type": "edgeCut" } & EdgeCut | { "type": "edgeCutEdge" } & EdgeCutEdge | { "type": "helix" } & Helix;

/**
 * A command that may create or update artifacts on the TS side.  Because
 * engine commands are batched, we don't have the response yet when these are
 * created.
 */
export type ArtifactCommand = { 
/**
 * Identifier of the command that can be matched with its response.
 */
cmdId: string, 
/**
 * The source range that's the boundary of calling the standard
 * library, not necessarily the true source range of the command.
 */
range: SourceRange, 
/**
 * The engine command.  Each artifact command is backed by an engine
 * command.  In the future, we may need to send information to the TS side
 * without an engine command, in which case, we would make this field
 * optional.
 */
command: ModelingCmd, };

export type ArtifactGraph = { map: { [key in ArtifactId]: Artifact }, itemCount: number, };

export type Cap = { id: ArtifactId, subType: CapSubType, edgeCutEdgeIds: Array<ArtifactId>, sweepId: ArtifactId, pathIds: Array<ArtifactId>, 
/**
 * This is for the sketch-on-face plane, not for the cap itself.  Traverse
 * to the extrude and/or segment to get the cap's code_ref.
 */
faceCodeRef: CodeRef, 
/**
 * The command ID that got the data for this cap. Used for stable sorting.
 */
cmdId: string, };

export type CapSubType = "start" | "end";

export type CodeRef = { range: SourceRange, nodePath: NodePath, pathToNode: Array<[string | number, string]>, };

export type CompositeSolid = { id: ArtifactId, 
/**
 * Whether this artifact has been used in a subsequent operation
 */
consumed: boolean, subType: CompositeSolidSubType, 
/**
 * Index of this output in the expression result, for operations that
 * return multiple selectable bodies from one KCL variable.
 */
outputIndex?: number | null, 
/**
 * Constituent solids of the composite solid.
 */
solidIds: Array<ArtifactId>, 
/**
 * Tool solids used for asymmetric operations like subtract.
 */
toolIds: Array<ArtifactId>, codeRef: CodeRef, 
/**
 * This is the ID of the composite solid that this is part of, if any, as a
 * composite solid can be used as input for another composite solid.
 */
compositeSolidId?: ArtifactId | null, };

export type CompositeSolidSubType = "intersect" | "subtract" | "split" | "union";

export type EdgeCut = { id: ArtifactId, subType: EdgeCutSubType, consumedEdgeId: ArtifactId, edgeIds: Array<ArtifactId>, surfaceId?: ArtifactId | null, codeRef: CodeRef, };

export type EdgeCutEdge = { id: ArtifactId, edgeCutId: ArtifactId, surfaceId: ArtifactId, };

export type EdgeCutSubType = "fillet" | "chamfer" | "custom";

export type Helix = { id: ArtifactId, 
/**
 * The axis of the helix.  Currently this is always an edge ID, but we may
 * add axes to the graph.
 */
axisId: ArtifactId | null, codeRef: CodeRef, 
/**
 * The sweep, if any, that this Helix serves as the trajectory for.
 */
trajectorySweepId: ArtifactId | null, 
/**
 * Whether this artifact has been used in a subsequent operation
 */
consumed: boolean, };

export type Path = { id: ArtifactId, subType: PathSubType, planeId: ArtifactId, segIds: Array<ArtifactId>, 
/**
 * Whether this artifact has been used in a subsequent operation
 */
consumed: boolean, 
/**
 * The sweep, if any, that this Path serves as the base path for.
 * corresponds to `path_id` on the Sweep.
 */
sweepId?: ArtifactId | null, 
/**
 * The sweep, if any, that this Path serves as the trajectory for.
 */
trajectorySweepId: ArtifactId | null, solid2dId?: ArtifactId | null, codeRef: CodeRef, 
/**
 * This is the ID of the composite solid that this is part of, if any, as
 * this can be used as input for another composite solid.
 */
compositeSolidId?: ArtifactId | null, 
/**
 * For sketch paths, the ID of the sketch block this path was created
 * from. `None` for region paths and paths created in other ways.
 */
sketchBlockId?: ArtifactId | null, 
/**
 * For region paths, the ID of the sketch path this region was created
 * from. `None` for sketch paths.
 */
originPathId?: ArtifactId | null, 
/**
 * The hole, if any, from a subtract2d() call.
 */
innerPathId?: ArtifactId | null, 
/**
 * The `Path` that this is a hole of, if any. The inverse link of
 * `inner_path_id`.
 */
outerPathId?: ArtifactId | null, };

export type PathSubType = "sketch" | "region";

export type Plane = { id: ArtifactId, pathIds: Array<ArtifactId>, codeRef: CodeRef, };

export type PlaneOfFace = { id: ArtifactId, faceId: ArtifactId, codeRef: CodeRef, };

export type PrimitiveEdge = { id: ArtifactId, solidId: ArtifactId, codeRef: CodeRef, };

export type PrimitiveFace = { id: ArtifactId, solidId: ArtifactId, codeRef: CodeRef, };

export type Segment = { id: ArtifactId, pathId: ArtifactId, 
/**
 * If this artifact is a segment in a region, the segment in the original
 * sketch that this was derived from.
 */
originalSegId?: ArtifactId | null, surfaceId?: ArtifactId | null, edgeIds: Array<ArtifactId>, edgeCutId?: ArtifactId | null, codeRef: CodeRef, commonSurfaceIds: Array<ArtifactId>, };

export type SketchBlock = { id: ArtifactId, 
/**
 * The semantic standard plane name when the sketch block is on a standard plane.
 */
standardPlane?: PlaneName | null, 
/**
 * The concrete plane artifact ID backing the sketch block, when one is available.
 */
planeId?: ArtifactId | null, 
/**
 * The path artifact ID created from the sketch block, if there is one.
 * There are edge cases when a path isn't created, like when there are no
 * segments.
 */
pathId?: ArtifactId | null, codeRef: CodeRef, 
/**
 * The sketch ID (ObjectId) for the sketch scene object.
 */
sketchId: ApiObjectId, };

export type SketchBlockConstraint = { id: ArtifactId, 
/**
 * The sketch ID (ObjectId) that owns this constraint.
 */
sketchId: ApiObjectId, 
/**
 * The constraint ID (ObjectId) for the constraint scene object.
 */
constraintId: ApiObjectId, constraintType: SketchBlockConstraintType, codeRef: CodeRef, };

export type SketchBlockConstraintType = "angle" | "coincident" | "distance" | "diameter" | "equalRadius" | "fixed" | "horizontalDistance" | "verticalDistance" | "horizontal" | "linesEqualLength" | "midpoint" | "parallel" | "perpendicular" | "radius" | "symmetric" | "tangent" | "vertical";

export type Solid2d = { id: ArtifactId, pathId: ArtifactId, };

export type StartSketchOnFace = { id: ArtifactId, faceId: ArtifactId, codeRef: CodeRef, };

export type StartSketchOnPlane = { id: ArtifactId, planeId: ArtifactId, codeRef: CodeRef, };

/**
 * A sweep is a more generic term for extrude, revolve, loft, sweep, and blend.
 */
export type Sweep = { id: ArtifactId, subType: SweepSubType, pathId: ArtifactId, surfaceIds: Array<ArtifactId>, edgeIds: Array<ArtifactId>, codeRef: CodeRef, 
/**
 * ID of trajectory path for sweep, if any
 * Only applicable to SweepSubType::Sweep and SweepSubType::Blend, which
 * can use a second path-like input
 */
trajectoryId: ArtifactId | null, method: ExtrudeMethod, 
/**
 * Whether this artifact has been used in a subsequent operation
 */
consumed: boolean, };

export type SweepEdge = { id: ArtifactId, subType: SweepEdgeSubType, segId: ArtifactId, cmdId: string, sweepId: ArtifactId, commonSurfaceIds: Array<ArtifactId>, };

export type SweepEdgeSubType = "opposite" | "adjacent";

export type SweepSubType = "extrusion" | "extrusionTwist" | "revolve" | "revolveAboutEdge" | "loft" | "blend" | "sweep";

export type Wall = { id: ArtifactId, segId: ArtifactId, edgeCutEdgeIds: Array<ArtifactId>, sweepId: ArtifactId, pathIds: Array<ArtifactId>, 
/**
 * This is for the sketch-on-face plane, not for the wall itself.  Traverse
 * to the extrude and/or segment to get the wall's code_ref.
 */
faceCodeRef: CodeRef, 
/**
 * The command ID that got the data for this wall. Used for stable sorting.
 */
cmdId: string, };
