// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expr } from "./Expr.js";
import type { Node } from "./Node.js";
import type { Type } from "./Type.js";

export type AscribedExpression = { "type": "AscribedExpression", expr: Expr, ty: Node<Type>, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
