// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktraceItemKind } from "./BacktraceItemKind.js";
import type { SourceRange } from "./SourceRange.js";

export type BacktraceItem = { sourceRange: SourceRange, fnName: string | null, kind: BacktraceItemKind, };
