// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeoMeta } from './GeoMeta'
import type { Node } from './Node'
import type { TagDeclarator } from './TagDeclarator'
import type { UnitLen } from './UnitLen'

/**
 * A base path.
 */
export type BasePath = {
  /**
   * The from point.
   */
  from: [number, number]
  /**
   * The to point.
   */
  to: [number, number]
  units: UnitLen
  /**
   * The tag of the path.
   */
  tag: Node<TagDeclarator> | null
  /**
   * Metadata.
   */
  __geoMeta: GeoMeta
}
