// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeoMeta } from "./GeoMeta.js";
import type { UnitLength } from "./ModelingCmd.js";
import type { Node } from "./Node.js";
import type { TagDeclarator } from "./TagDeclarator.js";

/**
 * A base path.
 */
export type BasePath = { 
/**
 * The from point.
 */
from: [number, number], 
/**
 * The to point.
 */
to: [number, number], units: UnitLength, 
/**
 * The tag of the path.
 */
tag: Node<TagDeclarator> | null, 
/**
 * Metadata.
 */
__geoMeta: GeoMeta, };
