// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinaryOperator } from "./BinaryOperator.js";
import type { BinaryPart } from "./BinaryPart.js";

export type BinaryExpression = { "type": "BinaryExpression", operator: BinaryOperator, left: BinaryPart, right: BinaryPart, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
