// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArrayExpression } from "./ArrayExpression.js";
import type { ArrayRangeExpression } from "./ArrayRangeExpression.js";
import type { AscribedExpression } from "./AscribedExpression.js";
import type { BinaryExpression } from "./BinaryExpression.js";
import type { CallExpressionKw } from "./CallExpressionKw.js";
import type { IfExpression } from "./IfExpression.js";
import type { Literal } from "./Literal.js";
import type { MemberExpression } from "./MemberExpression.js";
import type { Name } from "./Name.js";
import type { Node } from "./Node.js";
import type { ObjectExpression } from "./ObjectExpression.js";
import type { SketchVar } from "./SketchVar.js";
import type { UnaryExpression } from "./UnaryExpression.js";

export type BinaryPart = { "type": "Literal" } & Node<Literal> | { "type": "Name" } & Node<Name> | { "type": "BinaryExpression" } & Node<BinaryExpression> | { "type": "CallExpressionKw" } & Node<CallExpressionKw> | { "type": "UnaryExpression" } & Node<UnaryExpression> | { "type": "MemberExpression" } & Node<MemberExpression> | { "type": "ArrayExpression" } & Node<ArrayExpression> | { "type": "ArrayRangeExpression" } & Node<ArrayRangeExpression> | { "type": "ObjectExpression" } & Node<ObjectExpression> | { "type": "IfExpression" } & Node<IfExpression> | { "type": "AscribedExpression" } & Node<AscribedExpression> | { "type": "SketchVar" } & Node<SketchVar>;
