// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotation } from "./Annotation.js";
import type { BodyItem } from "./BodyItem.js";
import type { Node } from "./Node.js";
import type { NonCodeMeta } from "./NonCodeMeta.js";

export type Block = { "type": "Block", items: Array<BodyItem>, non_code_meta?: NonCodeMeta, inner_attrs?: Array<Node<Annotation>>, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
