// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpressionStatement } from "./ExpressionStatement.js";
import type { ImportStatement } from "./ImportStatement.js";
import type { Node } from "./Node.js";
import type { ReturnStatement } from "./ReturnStatement.js";
import type { TypeDeclaration } from "./TypeDeclaration.js";
import type { VariableDeclaration } from "./VariableDeclaration.js";

export type BodyItem = { "type": "ImportStatement" } & Node<ImportStatement> | { "type": "ExpressionStatement" } & Node<ExpressionStatement> | { "type": "VariableDeclaration" } & Node<VariableDeclaration> | { "type": "TypeDeclaration" } & Node<TypeDeclaration> | { "type": "ReturnStatement" } & Node<ReturnStatement>;
