// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bounded edge.
 */
export type BoundedEdge = { 
/**
 * The id of the face this edge belongs to.
 */
faceId: string, 
/**
 * The id of the edge.
 */
edgeId: string, 
/**
 * A percentage bound of the edge, used to restrict what portion of the edge will be used.
 * Range (0, 1)
 */
lowerBound: number, 
/**
 * A percentage bound of the edge, used to restrict what portion of the edge will be used.
 * Range (0, 1)
 */
upperBound: number, };
