// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expr } from "./Expr.js";
import type { LabeledArg } from "./LabeledArg.js";
import type { Name } from "./Name.js";
import type { Node } from "./Node.js";
import type { NonCodeMeta } from "./NonCodeMeta.js";

export type CallExpressionKw = { "type": "CallExpressionKw", callee: Node<Name>, unlabeled: Expr | null, arguments: Array<LabeledArg>, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], nonCodeMeta?: NonCodeMeta, };
