// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node.js";
import type { SourceRange } from "./SourceRange.js";
import type { TagDeclarator } from "./TagDeclarator.js";

export type ChamferSurface = { 
/**
 * The id for the chamfer surface.
 */
faceId: string, 
/**
 * The tag.
 */
tag: Node<TagDeclarator> | null, 
/**
 * The id of the geometry.
 */
id: string, 
/**
 * The source range.
 */
sourceRange: SourceRange, };
