// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity.js";
import type { SourceRange } from "./SourceRange.js";
import type { Suggestion } from "./Suggestion.js";
import type { Tag } from "./Tag.js";

/**
 * An issue which occurred during parsing, etc. The severity determines whether
 * it's an error, warning, or other kind of issue.
 */
export type CompilationIssue = { sourceRange: SourceRange, message: string, suggestion: Suggestion | null, severity: Severity, tag: Tag, };
