// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConstraintLevels } from "./ConstraintLevels.js";
import type { SourceRange } from "./SourceRange.js";

/**
 * The constraint level.
 */
export type ConstraintLevel = { "ignore": { source_ranges: Array<SourceRange>, } } | { "none": { source_ranges: Array<SourceRange>, } } | { "partial": { source_ranges: Array<SourceRange>, levels: ConstraintLevels, } } | { "full": { source_ranges: Array<SourceRange>, } };
