// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CopilotCyclingCompletion } from "./CopilotCyclingCompletion.js";

export type CopilotCompletionResponse = { completions: Array<CopilotCyclingCompletion>, cancellationReason: string | null, };
