// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CopilotCyclingCompletion } from "./CopilotCyclingCompletion.js";
import type { CopilotLspCompletionParams } from "./CopilotLspCompletionParams.js";

export type CopilotCompletionTelemetry = { completion: CopilotCyclingCompletion, params: CopilotLspCompletionParams, };
