// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CopilotPosition } from "./CopilotPosition.js";
import type { CopilotRange } from "./CopilotRange.js";

export type CopilotCyclingCompletion = { uuid: string, displayText: string, text: string, range: CopilotRange, position: CopilotPosition, };
