// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OsInfo } from "./OsInfo.js";
import type { WebrtcStats } from "./WebrtcStats.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * The app info structure.
 * The Core Dump Info structure.
 */
export type CoreDumpInfo = { 
/**
 * The unique id for the core dump - this helps correlate uploaded files with coredump data.
 */
id: string, 
/**
 * The version of the app.
 */
version: string, 
/**
 * The git revision of the app.
 */
git_rev: string, 
/**
 * A timestamp of the core dump.
 */
timestamp: string, 
/**
 * If the app is running in desktop or the browser.
 */
desktop: boolean, 
/**
 * The os info.
 */
os: OsInfo, 
/**
 * The webrtc stats.
 */
webrtc_stats: WebrtcStats, 
/**
 * The kcl code the user is using.
 */
kcl_code: string, 
/**
 * The client state (singletons and xstate).
 */
client_state: JsonValue, };
