// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectTagFilletTagEntry } from "./DirectTagFilletTagEntry.js";
import type { SourceRange } from "./SourceRange.js";

/**
 * Metadata for one fillet/chamfer call that used `tags` directly (no stdlib call).
 */
export type DirectTagFilletMeta = { callSourceRange: SourceRange, tags: Array<DirectTagFilletTagEntry>, };
