// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Finding } from "./Finding.js";
import type { SourceRange } from "./SourceRange.js";
import type { Suggestion } from "./Suggestion.js";

/**
 * Specific discovered lint rule Violation of a particular Finding.
 */
export type Discovered = { 
/**
 * Zoo Lint Finding information.
 */
finding: Finding, 
/**
 * Further information about the specific finding.
 */
description: string, 
/**
 * Source code location.
 */
pos: SourceRange, 
/**
 * Is this discovered issue overridden by the programmer?
 */
overridden: boolean, 
/**
 * Suggestion to fix the issue.
 */
suggestion: Suggestion | null, };
