// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expr } from "./Expr.js";
import type { Node } from "./Node.js";
import type { Program } from "./Program.js";

export type ElseIf = { "type": "ElseIf", cond: Expr, then_val: Node<Program>, digest: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number] | null, };
