// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactGraph } from "./Artifact.js";
import type { CompilationIssue } from "./CompilationIssue.js";
import type { DefaultPlanes } from "./DefaultPlanes.js";
import type { KclValue } from "./KclValue.js";
import type { ModuleId } from "./ModuleId.js";
import type { ModulePath } from "./ModulePath.js";
import type { Operation } from "./Operation.js";

/**
 * Outcome of executing a program.  This is used in TS.
 */
export type ExecOutcome = { 
/**
 * Variables in the top-level of the root module. Note that functions will have an invalid env ref.
 */
variables: { [key in string]: KclValue }, 
/**
 * Operations that have been performed in execution order, for display in
 * the Feature Tree.
 */
operations: Array<Operation>, 
/**
 * Output artifact graph.
 */
artifactGraph: ArtifactGraph, 
/**
 * Non-fatal errors and warnings.
 */
issues: Array<CompilationIssue>, 
/**
 * File Names in module Id array index order
 */
filenames: { [key in ModuleId]: ModulePath }, 
/**
 * The default planes.
 */
defaultPlanes: DefaultPlanes | null, };
