// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArrayExpression } from "./ArrayExpression.js";
import type { ArrayRangeExpression } from "./ArrayRangeExpression.js";
import type { AscribedExpression } from "./AscribedExpression.js";
import type { BinaryExpression } from "./BinaryExpression.js";
import type { CallExpressionKw } from "./CallExpressionKw.js";
import type { FunctionExpression } from "./FunctionExpression.js";
import type { IfExpression } from "./IfExpression.js";
import type { KclNone } from "./KclNone.js";
import type { LabelledExpression } from "./LabelledExpression.js";
import type { Literal } from "./Literal.js";
import type { MemberExpression } from "./MemberExpression.js";
import type { Name } from "./Name.js";
import type { Node } from "./Node.js";
import type { ObjectExpression } from "./ObjectExpression.js";
import type { PipeExpression } from "./PipeExpression.js";
import type { PipeSubstitution } from "./PipeSubstitution.js";
import type { SketchBlock } from "./SketchBlock.js";
import type { SketchVar } from "./SketchVar.js";
import type { TagDeclarator } from "./TagDeclarator.js";
import type { UnaryExpression } from "./UnaryExpression.js";

/**
 * An expression can be evaluated to yield a single KCL value.
 */
export type Expr = { "type": "Literal" } & Node<Literal> | { "type": "Name" } & Node<Name> | { "type": "TagDeclarator" } & Node<TagDeclarator> | { "type": "BinaryExpression" } & Node<BinaryExpression> | { "type": "FunctionExpression" } & Node<FunctionExpression> | { "type": "CallExpressionKw" } & Node<CallExpressionKw> | { "type": "PipeExpression" } & Node<PipeExpression> | { "type": "PipeSubstitution" } & Node<PipeSubstitution> | { "type": "ArrayExpression" } & Node<ArrayExpression> | { "type": "ArrayRangeExpression" } & Node<ArrayRangeExpression> | { "type": "ObjectExpression" } & Node<ObjectExpression> | { "type": "MemberExpression" } & Node<MemberExpression> | { "type": "UnaryExpression" } & Node<UnaryExpression> | { "type": "IfExpression" } & Node<IfExpression> | { "type": "LabelledExpression" } & Node<LabelledExpression> | { "type": "AscribedExpression" } & Node<AscribedExpression> | { "type": "SketchBlock" } & Node<SketchBlock> | { "type": "SketchVar" } & Node<SketchVar> | { "type": "None" } & Node<KclNone>;
