// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StartOrEnd } from "./StartOrEnd.js";
import type { TagIdentifier } from "./TagIdentifier.js";

/**
 * A tag for a face.
 */
export type FaceTag = StartOrEnd | TagIdentifier;
