// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId.js";
import type { FaceParentSolid } from "./FaceParentSolid.js";
import type { ApiObjectId } from "./FrontendApi.js";
import type { UnitLength } from "./ModelingCmd.js";
import type { Point3d } from "./Point3d.js";

/**
 * A face.
 */
export type Face = { 
/**
 * The id of the face.
 */
id: string, 
/**
 * The artifact ID.
 */
artifactId: ArtifactId, 
/**
 * The scene object ID.
 */
objectId: ApiObjectId, 
/**
 * The tag of the face.
 */
value: string, 
/**
 * What should the face's X axis be?
 */
xAxis: Point3d, 
/**
 * What should the face's Y axis be?
 */
yAxis: Point3d, 
/**
 * The solid the face is on.
 */
parentSolid: FaceParentSolid, units: UnitLength, };
