// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId.js";
import type { FaceParentSolidView } from "./FaceParentSolidView.js";
import type { ApiObjectId } from "./FrontendApi.js";
import type { UnitLength } from "./ModelingCmd.js";
import type { Point3dView } from "./Point3dView.js";

export type FaceView = { id: string, artifactId: ArtifactId, objectId: ApiObjectId, value: string, xAxis: Point3dView, yAxis: Point3dView, parentSolid: FaceParentSolidView, units: UnitLength, };
