// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier.js";
import type { Node } from "./Node.js";
import type { Parameter } from "./Parameter.js";
import type { Program } from "./Program.js";

export type FunctionExpression = { "type": "FunctionExpression", name?: Node<Identifier> | null, params: Array<Parameter>, body: Node<Program>, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
