// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier.js";
import type { Node } from "./Node.js";
import type { Type } from "./Type.js";

export type FunctionType = { unnamed_arg: Node<Type> | null, named_args: Array<[Node<Identifier>, Node<Type>]>, return_type: Node<Type> | null, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
