// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sketch } from "./Sketch.js";
import type { Solid } from "./Solid.js";

/**
 * A set of geometry.
 */
export type Geometries = { "type": "Sketches" } & Array<Sketch> | { "type": "Solids" } & Array<Solid>;
