// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportedGeometry } from "./ImportedGeometry.js";
import type { Sketch } from "./Sketch.js";
import type { Solid } from "./Solid.js";

/**
 * A geometry including an imported geometry.
 */
export type GeometryWithImportedGeometry = { "type": "Sketch" } & Sketch | { "type": "Solid" } & Solid | { "type": "ImportedGeometry" } & ImportedGeometry;
