// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiObjectId, ApiPoint2d, ArcCtor, CircleCtor, Freedom, LineCtor, Number, PointCtor } from "./FrontendApi";
import type { NumericType } from "./NumericType";
import type { SegmentRepr } from "./SegmentRepr";
import type { Sketch } from "./Sketch";
import type { SketchSurface } from "./SketchSurface";
import type { SketchVarId } from "./SketchVarId";
import type { Solid } from "./Solid";
import type { TagIdentifier } from "./TagIdentifier";
import type { TyF64 } from "./TyF64";

export type AbstractSegment = { repr: SegmentRepr, };

export type ConstrainableLine2d = { vars: [ApiPoint2d<SketchVarId>, ApiPoint2d<SketchVarId>], objectId: ApiObjectId, };

export type ConstrainablePoint2d = { vars: ApiPoint2d<SketchVarId>, objectId: ApiObjectId, };

export type ConstrainablePoint2dOrOrigin = { "Point": ConstrainablePoint2d } | "Origin";

/**
 * A geometry.
 */
export type Geometry = { "type": "Sketch" } & Sketch | { "type": "Solid" } & Solid;

export type Segment = { 
/**
 * The engine ID.
 */
id: string, objectId: ApiObjectId, kind: SegmentKind, surface: SketchSurface, 
/**
 * The engine ID of the sketch that this is a part of.
 */
sketchId: string, tag: TagIdentifier | null, };

export type SegmentKind = { "point": { position: [TyF64, TyF64], ctor: PointCtor, freedom: Freedom | null, } } | { "line": { start: [TyF64, TyF64], end: [TyF64, TyF64], ctor: LineCtor, start_object_id: ApiObjectId, end_object_id: ApiObjectId, start_freedom: Freedom | null, end_freedom: Freedom | null, construction: boolean, } } | { "arc": { start: [TyF64, TyF64], end: [TyF64, TyF64], center: [TyF64, TyF64], ctor: ArcCtor, start_object_id: ApiObjectId, end_object_id: ApiObjectId, center_object_id: ApiObjectId, start_freedom: Freedom | null, end_freedom: Freedom | null, center_freedom: Freedom | null, construction: boolean, } } | { "circle": { start: [TyF64, TyF64], center: [TyF64, TyF64], ctor: CircleCtor, start_object_id: ApiObjectId, center_object_id: ApiObjectId, start_freedom: Freedom | null, center_freedom: Freedom | null, construction: boolean, } };

export type SketchConstraint = { kind: SketchConstraintKind, };

export type SketchConstraintKind = { "angle": { line0: ConstrainableLine2d, line1: ConstrainableLine2d, } } | { "distance": { points: [ConstrainablePoint2dOrOrigin, ConstrainablePoint2dOrOrigin], labelPosition?: ApiPoint2d<Number>, } } | { "radius": { points: [ConstrainablePoint2d, ConstrainablePoint2d], } } | { "diameter": { points: [ConstrainablePoint2d, ConstrainablePoint2d], } } | { "horizontalDistance": { points: [ConstrainablePoint2dOrOrigin, ConstrainablePoint2dOrOrigin], labelPosition?: ApiPoint2d<Number>, } } | { "verticalDistance": { points: [ConstrainablePoint2dOrOrigin, ConstrainablePoint2dOrOrigin], labelPosition?: ApiPoint2d<Number>, } };

export type SketchVar = { id: SketchVarId, initialValue: number, ty: NumericType, };

export type UnsolvedExpr = { "type": "Known" } & TyF64 | { "type": "Unknown" } & SketchVarId;

export type UnsolvedSegment = { 
/**
 * The engine ID.
 */
id: string, objectId: ApiObjectId, kind: UnsolvedSegmentKind, tag: TagIdentifier | null, };

export type UnsolvedSegmentKind = { "point": { position: [UnsolvedExpr, UnsolvedExpr], ctor: PointCtor, } } | { "line": { start: [UnsolvedExpr, UnsolvedExpr], end: [UnsolvedExpr, UnsolvedExpr], ctor: LineCtor, start_object_id: ApiObjectId, end_object_id: ApiObjectId, construction: boolean, } } | { "arc": { start: [UnsolvedExpr, UnsolvedExpr], end: [UnsolvedExpr, UnsolvedExpr], center: [UnsolvedExpr, UnsolvedExpr], ctor: ArcCtor, start_object_id: ApiObjectId, end_object_id: ApiObjectId, center_object_id: ApiObjectId, construction: boolean, } } | { "circle": { start: [UnsolvedExpr, UnsolvedExpr], center: [UnsolvedExpr, UnsolvedExpr], ctor: CircleCtor, start_object_id: ApiObjectId, center_object_id: ApiObjectId, construction: boolean, } };
