// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportedGeometry } from "./ImportedGeometry.js";
import type { Plane } from "./Plane.js";
import type { Solid } from "./Solid.js";

/**
 * Something that you can change the color of.
 */
export type HasAppearance = { "type": "importedGeometry" } & ImportedGeometry | { "type": "solidSet" } & Array<Solid> | { "type": "plane" } & Plane;
