// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Helix } from "./Helix.js";
import type { ImportedGeometry } from "./ImportedGeometry.js";
import type { Sketch } from "./Sketch.js";
import type { Solid } from "./Solid.js";

/**
 * Data for a solid, sketch, or an imported geometry.
 */
export type HideableGeometry = { "type": "importedGeometry" } & ImportedGeometry | { "type": "solidSet" } & Array<Solid> | { "type": "sketchSet" } & Array<Sketch> | { "type": "helixSet" } & Array<Helix>;
