// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GdtAnnotation } from "./GdtAnnotation.js";
import type { Helix } from "./Helix.js";
import type { ImportedGeometry } from "./ImportedGeometry.js";
import type { Plane } from "./Plane.js";
import type { Sketch } from "./Sketch.js";
import type { Solid } from "./Solid.js";

/**
 * Data for geometry that can be hidden.
 */
export type HideableGeometry = { "type": "importedGeometry" } & ImportedGeometry | { "type": "solidSet" } & Array<Solid> | { "type": "planeSet" } & Array<Plane> | { "type": "sketchSet" } & Array<Sketch> | { "type": "helixSet" } & Array<Helix> | { "type": "gdtAnnotationSet" } & Array<GdtAnnotation>;
