// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoundedEdge } from "./BoundedEdge.js";
import type { Face } from "./Face.js";
import type { GdtAnnotation } from "./GdtAnnotation.js";
import type { AbstractSegment, SketchConstraint, SketchVar } from "./Geometry.js";
import type { Helix } from "./Helix.js";
import type { ImportedGeometry } from "./ImportedGeometry.js";
import type { KclNone } from "./KclNone.js";
import type { Metadata } from "./Metadata.js";
import type { ModuleId } from "./ModuleId.js";
import type { Node } from "./Node.js";
import type { NumericType } from "./NumericType.js";
import type { Plane } from "./Plane.js";
import type { Sketch } from "./Sketch.js";
import type { Solid } from "./Solid.js";
import type { TagDeclarator } from "./TagDeclarator.js";
import type { TagIdentifier } from "./TagIdentifier.js";

/**
 * Any KCL value.
 */
export type KclValue = { "type": "Uuid", value: string, } | { "type": "Bool", value: boolean, } | { "type": "Number", value: number, ty: NumericType, } | { "type": "String", value: string, } | { "type": "SketchVar", value: SketchVar, } | { "type": "SketchConstraint", value: SketchConstraint, } | { "type": "Tuple", value: Array<KclValue>, } | { "type": "HomArray", value: Array<KclValue>, } | { "type": "Object", value: { [key in string]: KclValue }, constrainable: boolean, } | { "type": "TagIdentifier" } & TagIdentifier | { "type": "TagDeclarator" } & Node<TagDeclarator> | { "type": "GdtAnnotation", value: GdtAnnotation, } | { "type": "Plane", value: Plane, } | { "type": "Face", value: Face, } | { "type": "BoundedEdge", value: BoundedEdge, meta: Array<Metadata>, } | { "type": "Segment", value: AbstractSegment, } | { "type": "Sketch", value: Sketch, } | { "type": "Solid", value: Solid, } | { "type": "Helix", value: Helix, } | { "type": "ImportedGeometry" } & ImportedGeometry | { "type": "Function", value: null, } | { "type": "Module", value: ModuleId, } | { "type": "KclNone", value: KclNone, };
