// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expr } from "./Expr.js";
import type { Identifier } from "./Identifier.js";
import type { Node } from "./Node.js";

export type LabeledArg = { "type": "LabeledArg", label: Node<Identifier> | null, arg: Expr, };
