// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitAngle } from './UnitAngle'
import type { UnitLen } from './UnitLen'

export type MetaSettings = {
  defaultLengthUnits: UnitLen
  defaultAngleUnits: UnitAngle
  kclVersion: string
}
