// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraOrbitType } from './CameraOrbitType'
import type { CameraProjectionType } from './CameraProjectionType'
import type { DefaultTrue } from './DefaultTrue'
import type { MouseControlType } from './MouseControlType'
import type { UnitLength } from './UnitLength'

/**
 * Settings that affect the behavior while modeling.
 */
export type ModelingSettings = {
  /**
   * The default unit to use in modeling dimensions.
   */
  base_unit?: UnitLength
  /**
   * The projection mode the camera should use while modeling.
   */
  camera_projection?: CameraProjectionType
  /**
   * The methodology the camera should use to orbit around the model.
   */
  camera_orbit?: CameraOrbitType
  /**
   * The controls for how to navigate the 3D view.
   */
  mouse_controls?: MouseControlType
  /**
   * Toggle touch controls for 3D view navigation
   */
  enable_touch_controls?: DefaultTrue
  /**
   * Highlight edges of 3D objects?
   */
  highlight_edges?: DefaultTrue
  /**
   * Whether or not Screen Space Ambient Occlusion (SSAO) is enabled.
   */
  enable_ssao?: DefaultTrue
  /**
   * Whether or not to show a scale grid in the 3D modeling view
   */
  show_scale_grid?: boolean
}
