// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModulePath } from "./ModulePath.js";

export type ModuleSource = { path: ModulePath, source: string, };
