// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotation } from "./Annotation.js";
import type { ModuleId } from "./ModuleId.js";

export type Node<T> = { start: number, end: number, moduleId: ModuleId, outerAttrs?: Array<Node<Annotation>>, preComments?: Array<string>, commentStart: number, } & T;
