// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node.js";
import type { NonCodeNode } from "./NonCodeNode.js";

export type NonCodeMeta = { nonCodeNodes: { [key in number]: Array<Node<NonCodeNode>> }, startNodes: Array<Node<NonCodeNode>>, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
