// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitAngle, UnitLength } from "./ModelingCmd.js";
import type { UnitType } from "./UnitType.js";

export type NumericType = { "type": "Known" } & UnitType | { "type": "Default", len: UnitLength, angle: UnitAngle, } | { "type": "Unknown" } | { "type": "Any" };
