// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitAngle } from './UnitAngle'
import type { UnitLen } from './UnitLen'
import type { UnitType } from './UnitType'

export type NumericType =
  | ({ type: 'Known' } & UnitType)
  | { type: 'Default'; len: UnitLen; angle: UnitAngle }
  | { type: 'Unknown' }
  | { type: 'Any' }
