// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node.js";
import type { NonCodeMeta } from "./NonCodeMeta.js";
import type { ObjectProperty } from "./ObjectProperty.js";

export type ObjectExpression = { "type": "ObjectExpression", properties: Array<Node<ObjectProperty>>, nonCodeMeta?: NonCodeMeta, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
