// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expr } from "./Expr.js";
import type { Identifier } from "./Identifier.js";
import type { Node } from "./Node.js";

export type ObjectProperty = { "type": "ObjectProperty", key: Node<Identifier>, value: Expr, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
