// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModuleId } from "./ModuleId.js";
import type { Operation } from "./Operation.js";

export type OperationsByModule = { map: { [key in ModuleId]: Array<Operation> }, };
