// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DefaultParamVal } from "./DefaultParamVal.js";
import type { Identifier } from "./Identifier.js";
import type { Node } from "./Node.js";
import type { Type } from "./Type.js";

/**
 * Parameter of a KCL function.
 */
export type Parameter = { "type": "Parameter", 
/**
 * Whether it's experimental.
 */
experimental?: boolean, 
/**
 * The parameter's label or name.
 */
identifier: Node<Identifier>, 
/**
 * The type of the parameter.
 * This is optional if the user defines a type.
 */
param_type: Node<Type> | null, 
/**
 * Is the parameter optional?
 * If so, what is its default value?
 * If this is None, then the parameter is required.
 * Defaults to None.
 */
default_value?: DefaultParamVal | null, 
/**
 * Functions may declare at most one parameter without label, prefixed by '@', and it must be the first parameter.
 */
labeled?: boolean, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
