// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandBarSettings } from './CommandBarSettings'
import type { ProjectAppSettings } from './ProjectAppSettings'
import type { ProjectModelingSettings } from './ProjectModelingSettings'
import type { TextEditorSettings } from './TextEditorSettings'

/**
 * High level project settings.
 */
export type PerProjectSettings = {
  /**
   * The settings for the Design Studio.
   */
  app: ProjectAppSettings
  /**
   * Settings that affect the behavior while modeling.
   */
  modeling: ProjectModelingSettings
  /**
   * Settings that affect the behavior of the KCL text editor.
   */
  text_editor: TextEditorSettings
  /**
   * Settings that affect the behavior of the command bar.
   */
  command_bar: CommandBarSettings
}
