// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectAppSettings } from "./ProjectAppSettings.js";
import type { ProjectMetaSettings } from "./ProjectMetaSettings.js";
import type { ProjectModelingSettings } from "./ProjectModelingSettings.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * High level project settings.
 */
export type PerProjectSettings = { 
/**
 * Information about the project itself.
 * Choices about how settings are merged have prevent me (lee) from easily
 * moving this out of the settings structure.
 */
meta: ProjectMetaSettings, 
/**
 * The settings for the Design Studio.
 */
app: ProjectAppSettings, 
/**
 * Settings that affect the behavior while modeling.
 */
modeling: ProjectModelingSettings, } & ({ [key in string]: number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null });
