// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId.js";
import type { ApiObjectId } from "./FrontendApi.js";
import type { PlaneKindView } from "./PlaneKindView.js";
import type { Point3dView } from "./Point3dView.js";

export type PlaneView = { artifactId: ArtifactId, id: string, objectId: ApiObjectId | null, kind: PlaneKindView, origin: Point3dView, xAxis: Point3dView, yAxis: Point3dView, zAxis: Point3dView, };
