// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitLen } from './UnitLen'

export type Point3d = { x: number; y: number; z: number; units: UnitLen }
