// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotation } from "./Annotation.js";
import type { BodyItem } from "./BodyItem.js";
import type { Node } from "./Node.js";
import type { NonCodeMeta } from "./NonCodeMeta.js";
import type { Shebang } from "./Shebang.js";

/**
 * A KCL program top level, or function body.
 */
export type Program = { body: Array<BodyItem>, nonCodeMeta?: NonCodeMeta, shebang?: Node<Shebang> | null, innerAttrs?: Array<Node<Annotation>>, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
