// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectTagFilletMeta } from "./DirectTagFilletMeta.js";
import type { EdgeRefactorMeta } from "./EdgeRefactorMeta.js";
import type { LegacyAngleRefactorMeta } from "./LegacyAngleRefactorMeta.js";

/**
 * Unified metadata stream for Z0006 and future execution-backed refactors.
 */
export type RefactorMetadata = { "kind": "edgeRefactor", "data": EdgeRefactorMeta } | { "kind": "directTagFillet", "data": DirectTagFilletMeta } | { "kind": "legacyAngle", "data": LegacyAngleRefactorMeta };
