// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from "./Block.js";
import type { LabeledArg } from "./LabeledArg.js";
import type { Node } from "./Node.js";
import type { NonCodeMeta } from "./NonCodeMeta.js";

export type SketchBlock = { "type": "SketchBlock", arguments: Array<LabeledArg>, body: Node<Block>, non_code_meta?: NonCodeMeta, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
