// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Plane } from "./Plane.js";
import type { PlaneData } from "./PlaneData.js";
import type { Solid } from "./Solid.js";

/**
 * Data for start sketch on.
 * You can start a sketch on a plane or an solid.
 */
export type SketchData = PlaneData | Plane | Solid;
