// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId.js";
import type { BasePathView } from "./BasePathView.js";
import type { UnitLength } from "./ModelingCmd.js";
import type { PathView } from "./PathView.js";
import type { ProfileClosedView } from "./ProfileClosedView.js";
import type { SketchSurfaceView } from "./SketchSurfaceView.js";
import type { TagIdentifierView } from "./TagIdentifierView.js";

export type SketchView = { type: "Sketch", id: string, paths: Array<PathView>, innerPaths?: Array<PathView>, on: SketchSurfaceView, start: BasePathView, tags?: { [key in string]: TagIdentifierView }, artifactId: ArtifactId, originalId: string, units: UnitLength, isClosed: ProfileClosedView, };
