// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node.js";
import type { NumericLiteral } from "./NumericLiteral.js";

export type SketchVar = { "type": "SketchVar", initial: Node<NumericLiteral> | null, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
