// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FaceView } from "./FaceView.js";
import type { PlaneView } from "./PlaneView.js";

export type SketchSurfaceView = { "type": "plane" } & PlaneView | { "type": "face" } & FaceView;
