// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId.js";
import type { EdgeCutView } from "./EdgeCutView.js";
import type { ExtrudeSurfaceView } from "./ExtrudeSurfaceView.js";
import type { UnitLength } from "./ModelingCmd.js";
import type { SolidCreatorView } from "./SolidCreatorView.js";
import type { TagIdentifierView } from "./TagIdentifierView.js";

export type SolidView = { type: "Solid", id: string, originalId: string, topologyId: string, artifactId: ArtifactId,
/**
 * Surface summaries are retained for the debug memory pane.
 */
value: Array<ExtrudeSurfaceView>, faces?: { [key in string]: TagIdentifierView }, sketch: SolidCreatorView, startCapId: string | null, endCapId: string | null, edgeCuts?: Array<EdgeCutView>, units: UnitLength, sectional: boolean, };
