// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportedGeometry } from "./ImportedGeometry.js";
import type { Solid } from "./Solid.js";

/**
 * Data for a solid or an imported geometry.
 */
export type SolidOrImportedGeometry = { "type": "importedGeometry" } & ImportedGeometry | { "type": "solidSet" } & Array<Solid>;
