// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatorFace } from "./CreatorFace";
import type { Sketch } from "./Sketch";

/**
 * How a solid was created.
 */
export type SolidCreator = { "creatorType": "sketch" } & Sketch | { "creatorType": "face" } & CreatorFace | { "creatorType": "procedural" };
