// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceRange } from "./SourceRange.js";
import type { TagDeclaratorView } from "./TagDeclaratorView.js";

export type SurfaceView = { faceId: string, tag: TagDeclaratorView | null, id: string, sourceRange: SourceRange, };
