// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Segment } from "./Geometry.js";
import type { Helix } from "./Helix.js";
import type { Sketch } from "./Sketch.js";

/**
 * A path to sweep along.
 */
export type SweepPath = Sketch | Helix | Array<Segment>;
