// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier.js";
import type { ItemVisibility } from "./ItemVisibility.js";
import type { Node } from "./Node.js";
import type { Type } from "./Type.js";

export type TypeDeclaration = { "type": "TypeDeclaration", name: Node<Identifier>, args: Array<Node<Identifier>> | null, visibility?: ItemVisibility, alias: Node<Type> | null, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
