// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnumDeclaration } from "./EnumDeclaration.js";
import type { Node } from "./Node.js";
import type { Type } from "./Type.js";

/**
 * What a type declaration declares its name to be.
 *
 * A discriminated definition rather than optional fields so that impossible
 * combinations (e.g. a declaration that is both an alias and an enum) cannot
 * be represented. A future nominal product (struct) definition would be added
 * as another variant here.
 */
export type TypeDeclarationDefinition = { "type": "Bare" } | { "type": "Alias", ty: Node<Type>, } | { "type": "Enum" } & EnumDeclaration;
