// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A unit of angle.
 */
export type UnitAngle =
  | { type: 'Degrees' }
  | { type: 'Radians' }
  | { type: 'Unknown' }
