// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A unit of length.
 */
export type UnitLen =
  | { type: 'Mm' }
  | { type: 'Cm' }
  | { type: 'M' }
  | { type: 'Inches' }
  | { type: 'Feet' }
  | { type: 'Yards' }
  | { type: 'Unknown' }
